# Generated by Django 2.1 on 2021-05-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Designer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=15)),
                ('Product_Name', models.CharField(max_length=15)),
                ('items_json', models.CharField(max_length=5000, verbose_name='username')),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('address', models.TextField(default='')),
                ('city', models.CharField(max_length=111)),
                ('state', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=111)),
                ('phone', models.CharField(default='', max_length=111)),
                ('payment_mode', models.CharField(max_length=150)),
                ('product_total', models.CharField(max_length=150)),
                ('Designer_name', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Designer.Designer')),
            ],
        ),
    ]
