# Generated by Django 5.0 on 2024-01-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_items_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Designer_name',
        ),
    ]
