# Generated by Django 2.1 on 2021-05-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Qty', models.DecimalField(decimal_places=0, default='', max_digits=2)),
                ('Total', models.DecimalField(decimal_places=2, default='', max_digits=8)),
            ],
        ),
    ]
