# Generated by Django 2.1 on 2021-05-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('City', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Pincode', models.DecimalField(decimal_places=0, default='', max_digits=6)),
                ('City_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='City.City')),
            ],
        ),
    ]
