# Generated by Django 2.1 on 2021-05-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Mobile_number', models.CharField(max_length=13)),
                ('Profile_pic', models.ImageField(upload_to='DesignerProfilePic')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DesignerBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('user_phone', models.CharField(max_length=150)),
                ('user_address', models.TextField()),
                ('Payment_status', models.BooleanField(default=False)),
                ('Payment_total', models.CharField(max_length=15)),
            ],
        ),
    ]
