# Generated by Django 2.1 on 2021-05-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Status', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], default='1', max_length=1)),
            ],
        ),
    ]
