# Generated by Django 2.1 on 2021-05-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Designer', '0001_initial'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('image', models.ImageField(upload_to='prod_img')),
                ('Description', models.TextField(default='')),
                ('short_Description', models.TextField(default='')),
                ('Additional_information', models.TextField(default='')),
                ('Product_sku', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('Product_Qty', models.DecimalField(decimal_places=0, default='', max_digits=2)),
                ('Product_status', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], default='1', max_length=1)),
                ('Cat_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.Category')),
                ('Designers_Name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Designer.Designer')),
            ],
        ),
    ]
