# Generated by Django 2.1 on 2021-05-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('State', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('State_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='State.State')),
            ],
        ),
    ]
